# Generated by Django 4.2.20 on 2025-05-28 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_profile_email_notifications_profile_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_public',
        ),
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_analysis_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
