# Generated by Django 4.2.20 on 2025-05-29 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_is_public_analysishistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisHistory',
        ),
    ]
